name: clova
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py310h06a4308_0
  - python=3.10.12=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==1.4.0
      - accelerate==0.20.3
      - addict==2.4.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - annotated-types==0.5.0
      - anyio==3.7.1
      - asttokens==2.2.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - augly==1.0.0
      - autocommand==2.2.2
      - backcall==0.2.0
      - backports-csv==1.0.7
      - beautifulsoup4==4.12.2
      - blis==0.7.10
      - cachetools==5.3.1
      - catalogue==2.0.9
      - certifi==2023.7.22
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - cheroot==10.0.0
      - cherrypy==18.8.0
      - click==8.1.7
      - cmake==3.27.2
      - confection==0.1.1
      - contourpy==1.1.0
      - cryptography==41.0.3
      - cycler==0.11.0
      - cymem==2.0.7
      - debugpy==1.6.7.post1
      - decorator==5.1.1
      - diffusers==0.21.4
      - distro==1.9.0
      - exceptiongroup==1.1.3
      - executing==1.2.0
      - face-detection==0.2.2
      - fairscale==0.4.4
      - feedparser==6.0.10
      - filelock==3.12.2
      - fire==0.5.0
      - fonttools==4.42.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - ftfy==6.1.1
      - future==0.18.3
      - grpcio==1.57.0
      - h11==0.14.0
      - httpcore==0.18.0
      - httpx==0.25.0
      - huggingface-hub==0.16.4
      - idna==3.4
      - importlib-metadata==6.8.0
      - inflect==7.0.0
      - iopath==0.1.10
      - ipykernel==6.15.2
      - ipython==8.14.0
      - jaraco-collections==4.3.0
      - jaraco-context==4.3.0
      - jaraco-functools==3.9.0
      - jaraco-text==3.11.1
      - jedi==0.19.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - jupyter-client==8.3.1
      - jupyter-core==5.3.1
      - kiwisolver==1.4.4
      - langcodes==3.3.0
      - lit==16.0.6
      - lxml==4.9.3
      - markdown==3.4.4
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - more-itertools==10.1.0
      - mpmath==1.3.0
      - multidict==6.0.4
      - murmurhash==1.0.9
      - mysqlclient==2.2.0
      - nest-asyncio==1.5.7
      - networkx==3.1
      - nltk==3.8.1
      - numpy==1.25.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - openai==1.2.0 
      - opencv-python==4.8.0.76
      - packaging==23.1
      - pandas==2.0.3
      - parso==0.8.3
      - pathy==0.10.2
      - pattern==3.6
      - pdfminer-six==20221105
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.2.0
      - platformdirs==3.10.0
      - portalocker==2.7.0
      - portend==3.2.0
      - preshed==3.0.8
      - prompt-toolkit==3.0.39
      - protobuf==4.24.1
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.7
      - pycparser==2.21
      - pydantic==2.3.0
      - pydantic-core==2.6.3
      - pygments==2.16.1
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - python-docx==0.8.11
      - python-magic==0.4.27
      - pytz==2023.3
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - regex==2023.8.8
      - replicate==0.15.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - ruamel-yaml==0.17.32
      - ruamel-yaml-clib==0.2.7
      - safetensors==0.3.2
      - scipy==1.11.2
      - sentencepiece==0.1.99
      - sgmllib3k==1.0.0
      - six==1.16.0
      - smart-open==6.3.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - spacy==3.6.1
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - srsly==2.4.7
      - stack-data==0.6.2
      - supervision==0.6.0
      - sympy==1.12
      - tabulate==0.9.0
      - tempora==5.5.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.1
      - tensorboardx==2.6.2.2
      - termcolor==2.3.0
      - thinc==8.1.12
      - timm==0.4.12
      - tokenizers==0.13.3
      - tomli==2.0.1
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.9.0
      - transformers==4.33.1
      - triton==2.0.0
      - typer==0.9.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - urllib3==1.26.16
      - wasabi==1.1.2
      - wcwidth==0.2.6
      - werkzeug==2.3.7
      - yapf==0.40.1
      - yarl==1.9.2
      - zc-lockfile==3.0.post1
      - zipp==3.16.2
